server:
  port: 7979
  servlet:
    context-path: /identity


spring:
  datasource:
    url: "jdbc:mysql://localhost:3307/identity_service"
    username: root
    password: root

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

jwt:
  signerKey: '1TjXchw5FloESb63Kc+DFhTARvpWL4jUGCwfGWxuG5SIf/1y/LgJxHnMqaF6A/ij'
  valid-duration: 3600
  refreshable-duration: 360000
